#indica la version de Docker Compose utilizada
version: '3.7'
#Bloque de servicios, indica los contenedores a utilizar.
services:
  app-web:       #nombre del servicio
    image: enmanuelcruzdejesus/barcamp-app-docker #imagen utilizada.
    ports:          #puertos que estaran expuestos.
      - 8080:8080
    environment:    #variable de ambiente
      - spring.datasource.url=jdbc:mysql://base-datos-app-web:3306/Barcampdb
      - spring.datasource.username=root
      - spring.datasource.password=entrada01
    networks:    #red para conectar los equipos.
      - my-network
    volumes:
      - my-vol:/tmp/
    depends_on:   #indica que primero debe subir los servicios indicados.
      - base-datos-app-web

  base-datos-app-web:
    image: mysql:5.7.26
    ports:
      - 33006:3306
    environment:
      - MYSQL_ROOT_PASSWORD=entrada01
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=entrada01
      - MYSQL_DATABASE=Barcampdb
    volumes:   #volumen de datos utilizado.
      - ~/mydb:/var/lib/mysql
    networks:
      - my-network

  angular:
    image: enmanuelcruzdejesus/barcamp-front
    container_name: angular
    ports:
      - 80:80
    depends_on:
      - app-web
    networks:
      - my-network



networks:  #bloque para las redes
  my-network:   #indicando la red definida

volumes: #Bloque para definir los volumenes
  my-vol:
